### ISSUE TITLE
RSData Development Check List

### ISSUE THREAD

**Issue by TehKittyCat** [rswiki/RSData#1]
We need to develop an actionable plan for RSData, so I am creating this issue for us to check off our progress and track ideas. For now it is more stream of consciousness than a plan.

Check list:
- [x] Setup repository for RSData.
- [ ] Implement whitelist and named APIs at mw:rsdata, see #2 
- [ ] Implement memcaching of API/parser function results, see #3
- [ ] Implement HTTP retrieval of the APIs, see #4
- [ ] Implement action=rsdata MediaWiki API for RSData, see #5
- [ ] Potentially implement a #rsdata parser function, see #6
- [ ] Document everything code and usage wise.
- [ ] Implement proper error messages (in API and of class="error" variety for parser functions).
- [ ] Unit testing of all the things.
  - Caching is also tested. (Don't want 180 requests turning into 1800...)
- [ ] Port over good/fitting changes to RSHiscores.
- [ ] Get Wikia approval for adding to RuneScape Wiki.
  - Consider replacing RSHiscores with RSData (only if parser function is added).

Potential food-for-thought formats for mw:rsdata, action=rsdata and #rsdata:

```
# The format for hiscores without named parameters (while allowing skipping options) might be:
temp_hiscores http://services.runescape.com/m=temp-hiscores/getRankings.json?player=$1
temp_hiscores http://services.runescape.com/m=temp-hiscores/getRankings.json?player=$1&status=$2
# Potential named parameters version
temp_hiscores http://services.runescape.com/m=temp-hiscores/getRankings.json?player={player}
temp_hiscores http://services.runescape.com/m=temp-hiscores/getRankings.json?player={player}&status={status}
# Or (My preferred because it distinguishes optional parameters, Minecraft command help style)
temp_hiscores<player [status]> http://services.runescape.com/m=temp-hiscores/getRankings.json
# Or (Followed by this one, with example API parameters and comment too)
temp_hiscores<player status> http://services.runescape.com/m=temp-hiscores/getRankings.json <timeout=3, limit=2> # Fun, fun, fun.
# Or
temp_hiscores<player> http://services.runescape.com/m=temp-hiscores/getRankings.json
temp_hiscores<player, status> http://services.runescape.com/m=temp-hiscores/getRankings.json
# Or allow whatever the user wants parameter wise rather than whitelist. I'm not sure if allowing any parameter would be harmful.
temp_hiscores http://services.runescape.com/m=temp-hiscores/getRankings.json
# Or if we allow any parameters, then this might be nice for API parameters.
temp_hiscores<type=json,timeout=5> http://services.runescape.com/m=temp-hiscores/getRankings.json
# Or if type is mandatory, may be don't require named parameter.
temp_hiscores<json> http://services.runescape.com/m=temp-hiscores/getRankings.json

# Both options (name and status)
api.php?action=rsdata&src=temp_hiscores&query=TehKittyCat|archived
{{#rsdata:temp_hiscores|TehKittyCat|archived}}
# Without status
api.php?action=rsdata&src=temp_hiscores&query=TehKittyCat
{{#rsdata:temp_hiscores|TehKittyCat}}

# Named parameter version
api.php?action=rsdata&src=temp_hiscores&rsname=TehKittyCat&rsstatus=archived
{{#rsdata:temp_hiscores|name=TehKittyCat|status=archived}}
```

**Comment by onei** [comment]
I'm going to split some of these out so it's easier to comment on them going forward and hopefully be a little easier to match them to PRs :)
